### PR TITLE
>2x speedup of crawling SNPedia

### PR DESCRIPTION
**Pull request by mikolajz**
Maybe you are interested in this as well

### CODE REVIEW

**Comment by mentatpsi** [comment]
Hi,

There is considerable documentation on the presence of ambiguous flips related to orientation that prevent me from wanting to merge this code.

Additionally, these code changes are to the fundamental structure of the application that I'd like to avoid making changes to.

**Comment by mentatpsi** [comment]
Looking through the changes, they are very nicely thought out and do look like good improvements. Don't intend any insult, your coding is very good :).

**Comment by mentatpsi** [comment]
Let me know if you ever need a recommendation :)

**Comment by mikolajz** [comment]
No problem. I will continue working on it in my fork, since I want to add VCF file support to get a bigger picture. Once it's done, maybe it will be worth to add a link from your README to my tree?

**Comment by mentatpsi** [comment]
Regarding VCF file support, please see the below:
[Bioinformatics Stack Exchange: Converting a Dante Lab VCF file](https://bioinformatics.stackexchange.com/questions/20700/converting-a-dante-lab-vcf-file)

**Comment by mentatpsi** [comment]
As well as
[Bioinformatics Stack Exchange: How to Generate RSID values locally from VCF file](https://bioinformatics.stackexchange.com/questions/20713/how-to-generate-rsid-values-locally-from-vcf-file)

**Comment by mikolajz** [comment]
Hi, FYI in my tree I have added VCF support and tried to properly support orientations by using the reference genome field of SNPedia and `pyliftover` (there is also a warning to be cautious when orientation != stabilized orientation). I remember you don't want to merge these and, of course, that's your decision to make, but maybe you would add a link to my fork in the README.md if someone would be interested in it?

**Comment by mentatpsi** [comment]
Hi,

A bit about myself, I have an introductory knowledge of Computational Biology formulated in Academia research software development, with two Publications I've worked on that can be found online if interested. This space is incredibly rich and complex, and this application is designed to minimize the complexity by merely providing a one to one look up in a way that does not add any bioinformatics methods. I know Konstantin Tretyakov, author of pyliftover is well published and involved in bioinformatics research.

As additional research, I saw that convert_coordinate of the pyliftover library that you're using can return a list of possible conversions with conversion_chain_score returned in a tuple to highlight confidence score in the conversion if there's more than one. This confidence score, whether provided to the user or not, is something that would increase the complexity of this application, which is mostly a basic encyclopedic lookup tool. 

For a researcher, this complexity might be easier to navigate since they tend to be heavily involved not only in the Computational Methods, but also the Biological Knowledge to navigate this. I did not design this application solely for Bioinformatics researchers though, who I admire greatly. I designed this application for anyone that wants to make sense of their genome, whether someone deeply versed in Biology, or someone just starting out as a hobbyist.

Essentially, this application is designed to help a user find out where the knowledge article is that they can learn about their genotype. It performs a very basic bolding to map the two when their orientations match.

I appreciate and am grateful that you're involved in OSGenome. I hope that you can continue using it to your heart's content.

**Comment by mikolajz** [comment]
Hi,
  I, on the other hand, have no research experience (I come from a software
development background) but the struggle with the application I had as a
hobbyist was that the interesting info was buried in a lot of not really
interesting entries like "(A; A) common in Cilnvar". Hence, the solution of
sorting by importance, which requires better variant matching, which
requires handling of orientations. For me, this gives me a clearer picture
of what SNPedia can say about my genome. On the other hand, I also didn't
want to go into too much complexity, hence e.g., when I read that
convert_coordinates returns more than one coordinate in very rare
situations, I just take the first entry (like WSGExtract does).

Mikołaj

**Comment by mentatpsi** [comment]
Hi,

I understand your point, and I appreciate the depth of research you put into this investigation and contribution.

Regarding importance, 
I had created a feature branch with your work into the README of this application that shows your merge request and shows your contribution. Additionally, I had linked your Git profile into the README to showcase your work to give publicity for your contribution. 

If you look at the article the author of that library provides for the convert_coordinates you've leveraged [The Curse of Genomic Coordinates](https://fouryears.eu/2013/02/25/the-curse-of-genomic-coordinates/) he acknowledges the high complexity of this process. 

From what I've seen of your code, you're using the library to map the two reference assembly builds and then using a mapping to determine the complimentary base pair so that the orientation can be effectively mapped to SNPedia [Code: Genotype](https://github.com/mikolajz/OSGenome/blob/master/SNPedia/genotype.py). This is what I wanted to avoid. Primarily, because from my own understanding, there are genomic regions that are more structurally complex and contain inversions, duplications, and deletions, that this approach breaks down. While I understand that your approach is an interesting attempt to reduce the error rate, it is not fool proof and a user would need to develop a deep understanding of complex genomic structures to understand when this method breaks down. I didn't want to limit users who might not be in the field from using this application. It is certainly clever, and I appreciate the ingenuity that went into this attempt.

What I've seen with several users is seeing at risk genotype for some clinical disease (sometimes severe), and a great deal of stress from this result. This stress is not something I want to give people if it can be avoided. I want people to simply enjoy discovering their genome with a reduction of false positive as much as I'm able to produce given the limitations of DTC Gene testing.

**Pull request closed without merging**
